### ISSUE TITLE
Improvement Idea: Add /ebackup testftp

### ISSUE THREAD

**Issue by EpicLPer** [espidev/ebackup#11]
Heya!

Just discovered this plugin after failed attempts to get "Server Restorer"'s SFTP function to work...

I'd love to see a test function where you don't have to create a backup in order to see if the (S)FTP connection works. I saw that some others also opened issues with upload problems (which are now closed tho) so this would make it super easy to instantly test if stuff is working without having to wait for a new backup to finish :)

Thanks a lot and awesome work so far!

**Comment by espidev** [comment]
Added to v1.3.0
