### ISSUE TITLE
Backup fails sometimes

### ISSUE THREAD

**Issue by gamebuddiesempire** [espidev/ebackup#12]
This plugin worked perfectly for a while, but the last 2 days I received an error that a file is locked by another process. The server is the only running program. Perhaps this has something to do with autosave?

https://pastebin.com/R1jPsRnb

**Comment by espidev** [comment]
Hmm, strange. What I can probably do is actually display the file names, and skip it rather than error out. It most likely has nothing to do with autosave, as autosaves are disabled by the plugin. It may be caused by another plugin or separate process.

**Comment by gamebuddiesempire** [comment]
Thank you for the review. The backup zip is still created, but it is probably incomplete. Knowing which files aren't included would be very welcome to prevent problems with restoring backups, as well as getting the plugin or whatever causes the error fixed.

**Comment by espidev** [comment]
Sorry for the delay, please let me know if this build works for you: https://ci.espi.dev/job/ebackup/2/artifact/target/ebackup-1.1.0.jar

**Comment by gamebuddiesempire** [comment]
Don't worry about the delay. I found it rather quick actually. The fix worked and the file was worldedit.log.lck. Nothing important I believe.
