### ISSUE TITLE
Folders not excluding

### ISSUE THREAD

**Issue by Ekpoa** [espidev/ebackup#16]
`backup:
    pluginjars: true # The .jar files for the plugins
    pluginconfs: true # The data folder of each plugin
    ignore: # Files to ignore and NOT backup
        - 'plugins/eBackup/backups'
        - 'plugins/dynmap'
        - 'plugins/coreprotect'
        - 'logs'
        - 'cache'`

The coreprotect folder does not exclude from the backup. I have tried with only this plugin server. Same issue. I have check capitalization. Same Issue

Am I mising something?

**Comment by espidev** [comment]
i'm sorry I didn't see this issue being filed, but I'm pretty sure coreprotect is capitalized as `CoreProtect`

**Comment by espidev** [comment]
Closed to inactivity
