### ISSUE TITLE
seems like eBakcup go wrong

### ISSUE THREAD

**Issue by Chris-X2017** [espidev/ebackup#18]
https://www.hh110.xyz/wp-content/uploads/2021/02/QQ%E5%9B%BE%E7%89%8720210212213748.png
This is a picture of a mistake;I only install eBackup and LaggRemover

**Comment by espidev** [comment]
It seems that a backup was started when you were shutting down the server? That's unavoidable because the minecraft server will prevent the backup from happening, which causes that error

**Comment by espidev** [comment]
The error message won't occur with 1.1.4

**Comment by Chris-X2017** [comment]
I'm using the default file, which is backed up every day at 4:00, when I'm asleep, and I don't know what's going on.By the way, thank you very much, I'm going to use 1.1.4 right now

**Comment by Chris-X2017** [comment]
> The error message won't occur with 1.1.4

I'm using the default file, which is backed up every day at 4:00, when I'm asleep, and I don't know what's going on.By the way, thank you very much, I'm going to use 1.1.4 right now

**Comment by espidev** [comment]
You have to make sure a server restart is not scheduled at the exact same time

**Comment by Chris-X2017** [comment]
> You have to make sure a server restart is not scheduled at the exact same time

I did not set the server restart plan, is it Laggremover or the built-in function of the server?

**Comment by espidev** [comment]
If you don't have a restart system, don't worry about it.

**Comment by Chris-X2017** [comment]
> If you don't have a restart system, don't worry about it.

OK, thank you again!!!
