### ISSUE TITLE
Idea: Limit other backups from being made when an backup is running

### ISSUE THREAD

**Issue by MihneaShaff** [espidev/ebackup#19]
👋, if another backup is running and you try to make another one it will just throw an error and make an ~2MB file for the second backup - an check for this would be excellent.

**Comment by espidev** [comment]
Yikes, that somehow slipped my mind.
I'll try to get on this once my midterms are over. In a week if I've not replied, consider replying here to remind me.

**Comment by MihneaShaff** [comment]
> Yikes, that somehow slipped my mind.
> I'll try to get on this once my midterms are over. In a week if I've not replied, consider replying here to remind me.

Just did that 🤪

**Comment by espidev** [comment]
Please try this out, and let me know if it works: https://ci.espi.dev/job/ebackup/11/
