### ISSUE TITLE
Zip "other files" filenames

### ISSUE THREAD

**Issue by blackshot** [espidev/ebackup#2]
the "other files" and "plugin folder" filenames start with "\\" and there is a unnamed folder in the backup zipped files 
![image](https://user-images.githubusercontent.com/3688208/72681912-e63d9880-3aa6-11ea-9801-63635f220e68.png)

**Comment by espidev** [comment]
Is the server running on windows?

**Comment by blackshot** [comment]
linux, the image i shared is the .zip opened with Winrar in my pc

**Comment by espidev** [comment]
Okay, I have time in 2 days after my initial exam to test.
Could you send me your config too?

**Comment by espidev** [comment]
I need the config to test

**Comment by blackshot** [comment]
sorry i was vacationing.

here is the config.yml
https://pastebin.com/GpaN6PH9

**Comment by blackshot** [comment]
nevermind im using ServerRestorer now...
https://www.spigotmc.org/resources/serverrestorer.48853/

**Comment by espidev** [comment]
Should be fixed in 2.0.4
