### ISSUE TITLE
Backup when there are players on the server options

### ISSUE THREAD

**Issue by aRmark99** [espidev/ebackup#20]
To reduce disk space used

**Comment by aRmark99** [comment]
Just like the FTB backup quote "Can create backups only when players are online"
Reference: [https://www.curseforge.com/minecraft/mc-mods/ftb-backups?__cf_chl_jschl_tk__=819bf96b92a7b93cfda626cfe9dae51fa93ead3f-1615627036-0-AQXydr242zrRr94-9G8ffJPp3t0qkxRsbfeD4smiwwi8gtvpw-RChkvGF4CXmQf1n5cdpA7jrlsZoODyFrLT_e8wGK5GkwAmCwX1pi9_JDoVajmj0kLQhZoSLwhhSvqJnNmSipJ1ZjjUkE016hqsd7PDQQ6pcLi1HcwTY6nvshvGThEDzfy7M364v6GDLAoiKOrKSjDBB0a1Tox-Gb_M8BdLZpgcH8lCANyd8-Hy9ap3ebe_sJUa2K90H_4vS1OPRoH-I66SkuHEsGwtdzOjZ2D6aF32nmqIG4_By5vfGaa34f3daiyuwYPKxGmyCAe7llvoDE1EZqk2x3Btk8_3jOa4kSN2MdCbbBIY3xBi_4cv0ufdZRjBDKUZgvyMYzssgG62Po8JojCUgfGLrR-gG1btYYbXxtBJPGg---BkeloE]

**Comment by espidev** [comment]
Hmm, I don't have much time these days so I might forget to do this issue, ping in a week if I forget

So in between backup sessions, only backup if a player has joined between them?

**Comment by aRmark99** [comment]
yes or no?.. I don't really have an idea about the rules of it. I just think it would be nice to have an options in the config to set whether the backup start depending on the server is empty or not.

**Comment by espidev** [comment]
I said to ping me maybe in a week or two because I'm quite busy right now, and I might forget about this issue

**Comment by Romvnly-Gaming** [comment]
> I said to ping me maybe in a week or two because I'm quite busy right now, and I might forget about this issue

ping pong!

**Comment by espidev** [comment]
I'll attempt this on Thursday or Friday, as it will require quite a bit of testing

**Comment by prenetic** [comment]
+1 to this issue, being able to restrict backups to when players have logged in since the last backup interval reduces unnecessary SSD wear long-term.

**Comment by espidev** [comment]
Will be added in 1.3.0
You will need to manually enable the feature (add `only-backup-if-players-were-on: true` to your config.yml)
