### ISSUE TITLE
[Suggestion] Cloud Storage Services Support

### ISSUE THREAD

**Issue by Legit4K** [espidev/ebackup#21]
Not sure how this would be achieved but it'd be gold. The idea is to have the backups automatically upload to cloud services like Google Drive if chosen.

**Comment by espidev** [comment]
I don't really want to expand the featureset of ebackup too much in order to ensure reliability. You can try using another program to sync the backups to cloud services like Google Drive separately.

**Comment by rhld16** [comment]
Hey hope this doesn't seem like too much of a self-promotion but I'm a maintainer of  [DriveBackupV2](https://github.com/rhld16/DriveBackupV2) which is another backup plugin with cloud services support.

if you don't like this i am fully compliant to remove it

**Comment by Legit4K** [comment]
> Hey hope this doesn't seem like too much of a self-promotion but I'm a maintainer of [DriveBackupV2](https://github.com/rhld16/DriveBackupV2) which is another backup plugin with cloud services support.
> 
> if you don't like this i am fully compliant to remove it

Oh cool, is it still being maintained?
