### ISSUE TITLE
Backup Size

### ISSUE THREAD

**Issue by Romvnly-Gaming** [espidev/ebackup#24]
Hi, I've recently switched from ServerRestorer and I've just ran a test backup and it seems a low amount of compression is being applied to the backups which are causing huge file sizes. Perhaps add a compression level option in the configuration files?

**Comment by espidev** [comment]
I added it here: https://ci.espi.dev/job/ebackup/12/

If your config is already generated, add `compression-level`, like here: https://github.com/espidev/ebackup/blob/master/src/main/resources/config.yml

Just a word of warning that high compression levels take substantially longer.

**Comment by Romvnly-Gaming** [comment]
Like how longer are we talking here? With server restorer's level 9 compression it took around 7 minutes which is totally acceptable.

**Comment by espidev** [comment]
You can try it out for yourself. Java's zip API gives me compression levels from 0-8.

**Comment by espidev** [comment]
You can download it here: https://ci.espi.dev/job/ebackup/12/

**Comment by Romvnly-Gaming** [comment]
Alright, I will!

**Comment by Romvnly-Gaming** [comment]
fixed!
