### ISSUE TITLE
[Suggestion] Support incremental backup

### ISSUE THREAD

**Issue by Blocks233** [espidev/ebackup#29]
The idea is ebackup can make incremental backups between full backup.
It will save storage space, so that we can backup more frequently

**Comment by espidev** [comment]
I think that's outside the scope of the plugin, snapshots are not something that are easy to do well without destroying performance or being buggy (I'm not going to write a snapshotting system from scratch)

Using something like btrfs has snapshots built into the file system, and Docker could also provide a solution that's well tested
