### ISSUE TITLE
SFTP failure

### ISSUE THREAD

**Issue by Broyojo** [espidev/ebackup#3]
I am getting this error message when I am trying to backup my server to an ssh server:

[01:20:14 WARN]: 4: Failure
[01:20:14 WARN]:        at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2873)
[01:20:14 WARN]:        at com.jcraft.jsch.ChannelSftp.checkStatus(ChannelSftp.java:2486)
[01:20:14 WARN]:        at com.jcraft.jsch.ChannelSftp._put(ChannelSftp.java:651)
[01:20:14 WARN]:        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:475)
[01:20:14 WARN]:        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:365)
[01:20:14 WARN]:        at dev.espi.ebackup.BackupUtil.uploadSFTP(BackupUtil.java:154)
[01:20:14 WARN]:        at dev.espi.ebackup.BackupUtil.doBackup(BackupUtil.java:124)
[01:20:14 WARN]:        at dev.espi.ebackup.eBackup.lambda$onCommand$1(eBackup.java:123)
[01:20:14 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[01:20:14 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[01:20:14 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:20:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[01:20:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:20:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by espidev** [comment]
Could you please check your SFTP server log? Error 4 is a general sftp error...

**Comment by Broyojo** [comment]
Where would I find the SFTP server log?

**Comment by espidev** [comment]
Check /var/log/auth.log

**Comment by Broyojo** [comment]
ok here:
Feb 16 00:17:01 broyojo-X10SAE CRON[10482]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 00:17:01 broyojo-X10SAE CRON[10482]: pam_unix(cron:session): session closed for user root
Feb 16 01:01:30 broyojo-X10SAE sudo:  broyojo : TTY=unknown ; PWD=/home/broyojo ; USER=root ; COMMAND=/usr/lib/linuxmint/mintUpdate/checkAPT.py
Feb 16 01:01:30 broyojo-X10SAE sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Feb 16 01:01:36 broyojo-X10SAE sudo: pam_unix(sudo:session): session closed for user root
Feb 16 01:10:51 broyojo-X10SAE cinnamon-screensaver-pam-helper: gkr-pam: unlocked login keyring
Feb 16 01:17:01 broyojo-X10SAE CRON[13667]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 01:17:02 broyojo-X10SAE CRON[13667]: pam_unix(cron:session): session closed for user root
Feb 16 02:17:02 broyojo-X10SAE CRON[15474]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 02:17:02 broyojo-X10SAE CRON[15474]: pam_unix(cron:session): session closed for user root
Feb 16 03:01:30 broyojo-X10SAE sudo:  broyojo : TTY=unknown ; PWD=/home/broyojo ; USER=root ; COMMAND=/usr/lib/linuxmint/mintUpdate/checkAPT.py
Feb 16 03:01:30 broyojo-X10SAE sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Feb 16 03:01:35 broyojo-X10SAE sudo: pam_unix(sudo:session): session closed for user root
Feb 16 03:17:01 broyojo-X10SAE CRON[17840]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 03:17:01 broyojo-X10SAE CRON[17840]: pam_unix(cron:session): session closed for user root
Feb 16 04:17:01 broyojo-X10SAE CRON[19481]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 04:17:01 broyojo-X10SAE CRON[19481]: pam_unix(cron:session): session closed for user root
Feb 16 05:01:30 broyojo-X10SAE sudo:  broyojo : TTY=unknown ; PWD=/home/broyojo ; USER=root ; COMMAND=/usr/lib/linuxmint/mintUpdate/checkAPT.py
Feb 16 05:01:30 broyojo-X10SAE sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Feb 16 05:01:33 broyojo-X10SAE sudo: pam_unix(sudo:session): session closed for user root
Feb 16 05:17:01 broyojo-X10SAE CRON[21832]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 05:17:01 broyojo-X10SAE CRON[21832]: pam_unix(cron:session): session closed for user root
Feb 16 06:17:01 broyojo-X10SAE CRON[23542]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 06:17:01 broyojo-X10SAE CRON[23542]: pam_unix(cron:session): session closed for user root
Feb 16 06:25:01 broyojo-X10SAE CRON[23755]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 06:25:01 broyojo-X10SAE CRON[23755]: pam_unix(cron:session): session closed for user root
Feb 16 06:47:01 broyojo-X10SAE CRON[24345]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 06:47:01 broyojo-X10SAE CRON[24345]: pam_unix(cron:session): session closed for user root
Feb 16 07:01:30 broyojo-X10SAE sudo:  broyojo : TTY=unknown ; PWD=/home/broyojo ; USER=root ; COMMAND=/usr/lib/linuxmint/mintUpdate/checkAPT.py
Feb 16 07:01:30 broyojo-X10SAE sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Feb 16 07:01:36 broyojo-X10SAE sudo: pam_unix(sudo:session): session closed for user root
Feb 16 07:17:01 broyojo-X10SAE CRON[25877]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 07:17:01 broyojo-X10SAE CRON[25877]: pam_unix(cron:session): session closed for user root
Feb 16 07:30:01 broyojo-X10SAE CRON[26241]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 07:30:01 broyojo-X10SAE CRON[26241]: pam_unix(cron:session): session closed for user root
Feb 16 08:17:01 broyojo-X10SAE CRON[27503]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 08:17:01 broyojo-X10SAE CRON[27503]: pam_unix(cron:session): session closed for user root
Feb 16 08:40:28 broyojo-X10SAE cinnamon-screensaver-pam-helper: gkr-pam: unlocked login keyring

**Comment by espidev** [comment]
Did you attempt to run a backup before posting this log?

**Comment by Broyojo** [comment]
ok yeah you are right. this is from 8:00 which is most recent

Feb 16 08:17:01 broyojo-X10SAE CRON[27503]: pam_unix(cron:session): session opened for user root by (uid=0)
Feb 16 08:17:01 broyojo-X10SAE CRON[27503]: pam_unix(cron:session): session closed for user root
Feb 16 08:40:28 broyojo-X10SAE cinnamon-screensaver-pam-helper: gkr-pam: unlocked login keyring

**Comment by espidev** [comment]
don't see any issues here...
btw is this on a remove server? have you actually tried SSHing into it?

**Comment by Broyojo** [comment]
yeah I have sshed into it before. but at the same time I have an ssh
session connected to it. is that the problem?

**Comment by espidev** [comment]
No, it shouldn't be a problem. Is this your personal desktop? You might want to try seeing if you can SSH to a remote server and back.

**Comment by Broyojo** [comment]
yes, this is my personal computer. And yes, I can ssh to my remote server (which btw is a ec2 instance) and back.

**Comment by espidev** [comment]
try using scp on the remote server to copy (from the remote server) a file to your computer

just to test sftp

**Comment by espidev** [comment]
On the remote server:
```
$ scp ./file user@desktopip:/home/Downloads/file
```

**Comment by Broyojo** [comment]
ok it works.

**Comment by espidev** [comment]
Could I get your plugin config? Remember to remove the password and IP from it

**Comment by Broyojo** [comment]
crontask: '0 0 * * * *'

# CronTask format:
# * * * * * *
# | | | | | |
# | | | | | +---- Day of the Week   (1-7)
# | | | | +------ Month             (1-12)
# | | | +-------- Day of the Month  (1-31)
# | | +---------- Hour              (0-23)
# | +------------ Minute            (0-59)
# +-------------- Second            (0-59)

# A few more examples...
# crontask: '0 0 * * * *' This would make it every hour
# crontask: '0 0 4 * * 7' This would make it every sunday at 4 AM
# crontask: '0 0 4 1 * *' This would make it every first of the month at 4 AM

backup-format: 'backup {DATE}'

# The folder where to store the backups locally.
backup-path: 'plugins/eBackup/backups'

# The maximum backups stored. Will delete older backups when reached. (≤ 0 to disable)
# Note: this will only work with local backups (fallbacks included).
max-backups: 20

# FTP/SFTP settings and configuration.
# Backups saved here will not be auto-deleted.
ftp:
    enable: true
    type: sftp # ftp for ftp, sftp for ftp over ssh
    host: '_redacted_'
    port: 22
    user: '_redacted_'
    pass: '_redacted'
    path: 'server_backups'

# What you want in the backup.
# By default, everything will be backupped, you can remove folders in the ignore section
backup:
    pluginjars: true # The .jar files for the plugins
    pluginconfs: true # The data folder of each plugin
    ignore: # Files to ignore and NOT backup
        - 'plugins/eBackup/backups'
        - 'plugins/dynmap'
        - 'logs'
        - 'cache'

**Comment by espidev** [comment]
Are you sure the user has permission to copy into to /server_backups folder? Does that folder exist?

**Comment by Broyojo** [comment]
it does exist and very sure the user has permission to copy into that folder. I did an scp before into that folder and it worked.

**Comment by espidev** [comment]
Set the sshd_config LogLevel to DEBUG, restart the ssh server, and check the auth.log file after attempting to backup

I'm really not sure what the problem is...

**Comment by Broyojo** [comment]
on the ssh server or on my personal computer?

**Comment by espidev** [comment]
Personal computer (the destination)

**Comment by Broyojo** [comment]
I think you have some misunderstanding. The ssh server (ec2- one) is for remote backup. The minecraft server runs on my personal computer.

**Comment by espidev** [comment]
Oh...
When you tested SFTP, was it from your computer to the cloud?

Check the log file on the ec2 one

**Comment by Broyojo** [comment]
yes, when I tested scp, it was from my computer to the cloud. ok I changed the sshd_config file in the ec2 one. So should I give you the log file from the ec2 or from my personal computer?

**Comment by espidev** [comment]
Make sure you actually ran the backup before giving it to me. Be careful of sensitive information

Use the log file on the ec2

**Comment by Broyojo** [comment]
Ok I know the problem, I am very stupid. The disk space was used up on the remote ssh server! Thanks for you help I will just add more storage to my remote storage.

**Comment by espidev** [comment]
No problem
