### ISSUE TITLE
Make the path of ftp support Chinese

### ISSUE THREAD

**Issue by yahinstudio** [espidev/ebackup#39]
This plugin cannot be uploaded to the path with Chinese at present, can you fix it?

**Comment by espidev** [comment]
Please let me know if https://build.espi.dev/job/ebackup/23/ works.

This commit enables UTF-8 encoding for FTP if possible: https://github.com/espidev/ebackup/commit/52adfb14f8fab8b13fcd86d688c4ed64d4f3b964

**Comment by espidev** [comment]
Closing to inactivity, issue should be resolved in v1.3.1
