### ISSUE TITLE
Support more cron syntax

### ISSUE THREAD

**Issue by Syberiyxx** [espidev/ebackup#41]
I tried to use
` '0,30 * * * *' `
and
` '*/30 * * * *'`
 to get the backup to run every 30 minutes but I get a parsing error

https://frontbackend.com/linux/cron-every-30-minutes
https://stackoverflow.com/questions/584770/how-would-i-get-a-cron-job-to-run-every-30-minutes

**Comment by espidev** [comment]
eBackup has slightly different cron syntax because it also supports seconds, you need it like this:

`* 0,30 * * * *

'* */30 * * * *'

**Comment by espidev** [comment]
Closing to inactivity
