### ISSUE TITLE
Old backups not being removed on Paper 1.19.2 with version 1.3.1

### ISSUE THREAD

**Issue by 0Chameleon0** [espidev/ebackup#46]
I have been using ebackup for a long time with no issue in the past
I currently have 4 servers running paper 1.19.2 and am finding with ebackup 1.3.1 that it is not removing local backups exceding the max limit of 08

# The maximum backups stored. Will delete older backups when reached. (≤ 0 to disable)
# Note: this will only work with local backups (fallbacks included).
max-backups: 08

**Comment by espidev** [comment]
Just curious, could you try setting max-backups to just 8? (no zero before)

**Comment by 0Chameleon0** [comment]
I tried that, it reverted it to 08

**Comment by 0Chameleon0** [comment]
ill try again

**Comment by 0Chameleon0** [comment]
it kept without the zero this time, running a couple of backups to test now

**Comment by 0Chameleon0** [comment]
Yes, it is working now, I think what may have happened it when I first edited the server was running, I did do ebackup reload, but it reverted the change to have 08, this time i stopped te server, changed to not have the zero and started, the 4 servers seem to be OK now (the older backups past the last 8 are being removed.

Thankyou.
