### ISSUE TITLE
Disable Crontask?

### ISSUE THREAD

**Issue by CloudeLecaw** [espidev/ebackup#55]
We tried to disable grey out all crontasks because we use an other plugin to schedule the backup by commnd "ebackups backup"

On Serverstart i saw

```
[11:53:37] [Server thread/INFO]: [eBackup] Enabling eBackup v1.3.1
[11:53:37] [Server thread/INFO]: [eBackup] Initializing eBackup...
[11:53:37] [Server thread/INFO]: [eBackup] Configured the cron task to be: at 04:00
[11:53:37] [Server thread/INFO]: [eBackup] Plugin initialized!
```

i took a look back into the config.
```
#crontask: '59 59 23 * * *' # This would make it every day at 23:59:59
#crontask: '59 59 11 * * *' # This would make it every day at 11:59:59
# CronTask format:
# * * * * * *
# | | | | | |
# | | | | | +---- Day of the Week   (1-7)
# | | | | +------ Month             (1-12)
# | | | +-------- Day of the Month  (1-31)
# | | +---------- Hour              (0-23)
# | +------------ Minute            (0-59)
# +-------------- Second            (0-59)

# A few more examples...
# crontask: '0 0 * * * *' This would make it every hour
# crontask: '0 0 4 * * 7' This would make it every sunday at 4 AM
# crontask: '0 0 4 1 * *' This would make it every first of the month at 4 AM
# crontask: '0 30 3 */2 * *' This would make it at 3:30 AM every 2 days
```

ou see all contasks are written with # before so mean normaly the plugin should not start a autobackup anymore by it self.
Can you add a way to disable the crontask or fix this wrong behave?
Its not good if a plugin decided to automaticly doo something when the config is written to not do anything.

**Comment by espidev** [comment]
You can't remove a setting like that with yml, but you can set a really long duration with crontab so it never executes:

crontab: 0 0 0 31 2 1

**Comment by CloudeLecaw** [comment]
ohh i see so i can use invaile dates like the 31th Feb. Mon , that never will come.. right?

**Comment by espidev** [comment]
yes

**Comment by CloudeLecaw** [comment]
great solution i used it to skip the crontask. thank you for this nice suggestion <3
