### ISSUE TITLE
Implement key based authentication for sftp

### ISSUE THREAD

**Issue by Kenajcrap** [espidev/ebackup#6]
This is a marvelous plugin and definitely the best option for my little Minecraft server.
However, in the interest of keeping myself more secure when uploading a second backup to my private computer (due to a lack of a better option at the moment), and as a general improvement in feature set for the plugin, key based authentication would be a brilliant addition.
Unfortunately, I don't have the java expertise to do this modification myself.

**Comment by espidev** [comment]
Refer to the default config on the spigot page to add the config options to your config.yml
