### ISSUE TITLE
Error occurred while enabling eBackup v1.3.1 (Is it up to date?)

### ISSUE THREAD

**Issue by GreenArrowlol** [espidev/ebackup#65]
Check the new paste below

**Comment by GreenArrowlol** [comment]
https://pastebin.com/uc4BNcg9
it randomly broke btw after i changed my hosting

**Comment by GreenArrowlol** [comment]
not a ebackup issue, sorry.

**Comment by dusty3ntity** [comment]
Hey @GreenArrowlol did you have the same error?
```
Error occurred while enabling eBackup v1.3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: dev/espi/ebackup/CronUtil
```

If so, how did you fix that? It's quite confusing for me what's wrong here...

**Comment by GreenArrowlol** [comment]
> Hey @GreenArrowlol did you have the same error?
> 
> ```
> Error occurred while enabling eBackup v1.3.1 (Is it up to date?)
> java.lang.NoClassDefFoundError: dev/espi/ebackup/CronUtil
> ```
> 
> If so, how did you fix that? It's quite confusing for me what's wrong here...

issue was due to my server being infected, I have no idea how cuz I don't use any cracked plugins. I checked sources and many claimed it happened to them and all we have to do is redownload all the jars and reupload and start the server.
